export CORECLR_ENABLE_PROFILING=1
export CORECLR_PROFILER={36032161-FFC0-4B61-B559-F6C5D41BAE5A}
export CORECLR_NEWRELIC_HOME=/usr/local/newrelic-dotnet-agent
export CORECLR_PROFILER_PATH="${CORECLR_NEWRELIC_HOME}/libNewRelicProfiler.so"

export NEW_RELIC_DISTRIBUTED_TRACING_ENABLED=true
export NEW_RELIC_LICENSE_KEY="${NEW_RELIC_LICENSE_KEY}"
export NEW_RELIC_APP_NAME="chat-completion"
export NEW_RELIC_SEND_DATA_ON_EXIT=true
export NEW_RELIC_SEND_DATA_ON_EXIT_THRESHOLD_MS=2000
export NEW_RELIC_LOG=MyApp.log
export NEW_RELIC_LOG_ENABLED=true

export OPENAI_EXPERIMENTAL_ENABLE_OPEN_TELEMETRY=true

#dotnet Program.cs
$CORECLR_NEWRELIC_HOME/run.sh dotnet Program.cs